jwt.secret=superlongsecretkeythatisatleast64charactersforhs512algorithmandnowislongenough
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:mem:aistyle
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
huggingface.api-token=hf_test_token_placeholder
huggingface.primary-model=mistralai/Mistral-7B-Instruct-v0.3
huggingface.fallback-model=google/gemma-2-2b-it
huggingface.api-url=https://api-inference.huggingface.co/models/
server.port=8080
